name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
          
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        
      - name: Type check
        run: npx tsc --noEmit
        
      - name: Build
        run: pnpm build
        
      - name: Test CLI
        run: |
          echo "phase,section,topic,extractionPrompt" > test.csv
          echo "テスト,セクション1,トピック1,テスト用プロンプト" >> test.csv
          node dist/index.js test.csv output.json "テストテンプレート" "テスト用の説明"
          cat output.json