name: npm-publish

on:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'package.json'
      - '.npmrc'
      - '.github/workflows/publish.yml'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: '@salescore-inc'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - run: |
          pnpm publish --access restricted --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}